import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { LanguageProvider } from "@/context/LanguageContext"
import Header from "@/components/Header";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} antialiased`}>
        
      <Toaster
        toastOptions={{
          style: {
            background: '#1a1a1a',
            color: '#a1a1aa',
            border: '1px solid #2e2e2e',
            borderRadius: '12px',
            padding: '8px 12px',
            boxShadow: 'none',
            fontSize: '13px',
            maxWidth: 'fit-content',
          },
        
          success: {
            iconTheme: {
              primary: '#2e2e2e',
              secondary: '#a1a1aa',
            },
          },
        }}
        position="bottom-right"
        reverseOrder={false}
      />

        <LanguageProvider>
          <Header></Header>
          {children}</LanguageProvider>
      </body>
    </html>
  );
}
